[package]
name = "quik"
version = "0.1.0"
authors = ["Patrick Flynn <patrickf4664@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "parser",
    "compiler/x86",
    "compiler/aarch64"
]

[dependencies]
parser = { path = "parser" }
x86 = { path = "compiler/x86" }
aarch64 = { path = "compiler/aarch64" }
